export default {
  THMEM_CHANGE: 'THMEM_CHANGE',
  THMEM_INIT: 'THMEM_INIT',
  LOAD_POPULAR_REFRESH: 'LOAD_POPULAR_REFRESH',
  LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL',
  LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS', 
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULARLOAD_MOREH_SUCCESS' 
}